[package]
name = "chirp-8"
version = "0.1.0"
authors = ["Trikzon <trikzon@protonmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
ears = "0.8.0"
glutin = "0.26.0"
rand = "0.8.5"
thiserror = "1.0.24"

[build-dependencies]
gl_generator = "0.14.0"
